name: Test
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: enable buildkit
        shell: bash
        run: |
          echo '{"experimental": "enabled"}' > ~/.docker/config.json

      - name: Build
        run: docker-compose build test

      - name: Run
        run: docker-compose up -d test

      - name: Shutdown
        run: docker-compose down test

      - name: Docker Login
        if: ${{ env.DOCKER_USER != null }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ env.DOCKER_USER}}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Docker Push
        if: ${{ env.DOCKER_USER != null }}
        run: docker-compose push test

